### ISSUE TITLE
Problems running gwtDev with GWT 2.7.0-rc1

### ISSUE THREAD

**Issue by johnthad** [steffenschaefer/gwt-gradle-plugin#59]
I have been using the gwt-gradle-plugin 0.5 for some time (with Gradle 2.1). I'm now attempting to build my most current project with GWT 2.7.0-rc1 and MGWT 2.0.1-SNAPSHOT. I started by building the gwt-gradle-plugin 0.6-SNAPSHOT and using it to rebuild with GWT 2.7.0-rc1 a GWT library I wrote. That worked. However when I try to build my app, I get the following error:

```
java.lang.IncompatibleClassChangeError: class com.google.gwt.dev.javac.BytecodeSignatureMaker$CompileDependencyVisitor has interface org.objectweb.asm.ClassVisitor as super class
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
  at com.google.gwt.dev.javac.BytecodeSignatureMaker.visitCompileDependenciesInBytecode(BytecodeSignatureMaker.java:227)
  at com.google.gwt.dev.javac.BytecodeSignatureMaker.getCompileDependencySignature(BytecodeSignatureMaker.java:209)
  at com.google.gwt.dev.javac.CompiledClass.getSignatureHash(CompiledClass.java:166)
  at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:42)
  at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:37)
  at com.google.gwt.dev.javac.Dependencies.resolve(Dependencies.java:114)
  at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:366)
  at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:580)
  at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:513)
  at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:499)
  at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:668)
  at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:198)
  at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:82)
  at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
  at com.google.gwt.dev.codeserver.CodeServer.makeOutboxes(CodeServer.java:156)
  at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:118)
  at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:91)
  at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:50)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at com.google.gwt.dev.shell.SListener$1.run(SuperDevListener.java:82)
:gwtDev FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gwtDev'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

This app does build and run fine with Maven using GWT 2.7.0-rc1 and the gwt-maven-plugin (aside, the ability to launch the codeserver from devmode is _terrific_). However there are definitely things I've come to prefer about Gradle and I think I would like to stick with it.

**Comment by uhurusurfa** [comment]
I tried all the suggestions in a number of posts on the net and none of them worked.
After much experimenting, in the end I found that using the G1GC garbage collector on OSX made a big difference for me. If you are using ANT then you must make sure the build file launches the compiler with the G1GC garbage collector
